### ISSUE TITLE
nani the f*ck?

### ISSUE THREAD

**Issue by gapiyka** [ip-05/quizzus#1]
shems (?)__(?)

![gif](https://media.tenor.com/Aj8e7-DmhbUAAAAC/gochuumon-nani-nani.gif)

**Comment by nikolaichub** [comment]
![doc_2022-11-19_13-28-11 (1)](https://user-images.githubusercontent.com/61356191/202848513-e0ecc986-aa51-471e-8b1d-b25abbc81041.gif)
